### ISSUE TITLE
v86?

### ISSUE THREAD

**Issue by brandonros** [sha0coder/libscemu#19]
https://github.com/copy/v86 what could we do this?

**Comment by brandonros** [comment]
https://github.com/copy/v86/blob/4eb1e5035e91490c5aeebab45553d5043cd84b95/src/rust/cpu/instructions.rs

but no 64-bit

**Comment by brandonros** [comment]
https://github.com/copy/v86/pull/285/files

**Comment by sha0coder** [comment]
Nice project.
They use qemu and kvm-unit-test for testing.
really there are many ways of testing.

**Comment by sha0coder** [comment]
We can generate instructions with iced-x86  and brute-force emulate_instruction(ins) vs the inline asm.
But at the end the best thing is the diffing system you did, it's a bug hunter.
