### ISSUE TITLE
please refactor inspect/memory flags so that it makes it work like x64dbg memory changes

### ISSUE THREAD

**Issue by brandonros** [sha0coder/libscemu#41]
i need to be able to diff x64dbg CSV trace output (which is tracking memory writing as well as register writing) to see when we are writing the wrong value to memory (we currently are)

**Comment by sha0coder** [comment]
Currently the memory tracer don't trace the stack operations only the ones done with get_operand_value() set_operand_value()

one option is including it on stack_push32() and stack_push64()

**Comment by sha0coder** [comment]
I added the memory trace to pushes and pops.
