### ISSUE TITLE
Please update kernel32.rs in winapi64 

### ISSUE THREAD

**Issue by HongThatCong** [sha0coder/libscemu#55]
Please update kernel32.rs in winapi64 folder, support same APIs kernel32.rs in winapi32 folder.
From VirtualProctect to end.
Tks

**Comment by sha0coder** [comment]
I have to dedicate some time to 64bit api, most of the malware i analyze is 32bits but 64bits is the way.
regards.

**Comment by sha0coder** [comment]
I added more 64bits apis on commits:
https://github.com/sha0coder/libscemu/commit/e6e8941a7803aea39201344e0de89fcde200a78b
https://github.com/sha0coder/libscemu/commit/ebe03ed8c3524fcfe43a191d2e995a779f9c364b
https://github.com/sha0coder/libscemu/commit/e26ca00f4705866e665f8e83cabc0cbdc769597d
https://github.com/sha0coder/libscemu/commit/95240f71caaf2725ca2ac949c45efd2f3a2dce6d

**Comment by HongThatCong** [comment]
Tks @sha0coder
